[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install --no-cache-dir -r requirements.txt']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'python main.py'